Repository team-sonamu/backend-chongdae-market, pull requests merged in 2024-07, with the labels that each got.

#10 feat: 참여하기 API 구현
  src/main/java/woowacourse/chongdaemarket/global/exception/ErrorResponse.java
  src/main/java/woowacourse/chongdaemarket/global/exception/GlobalExceptionHandler.java
  src/main/java/woowacourse/chongdaemarket/global/exception/MarketException.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/GroupPurchaseController.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/ParticipationCountRequest.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/ParticipationCountResponse.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/exception/GroupPurchaseErrorCode.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/repository/GroupPurchase.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/repository/GroupPurchaseStatus.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/service/GroupPurchaseService.java
Labels: feature

#11 feat: 공동구매 목록 조회 API 구현
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/GroupPurchaseController.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/GroupPurchaseGetByIdResponse.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/GroupPurchaseResponse.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/GroupPurchaseResponses.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/service/GroupPurchaseService.java
Labels: feature

#13 refactor: 공동구매 도메인명 수정
  http/article.http
  src/main/java/woowacourse/chongdaemarket/article/controller/ArticleController.java
  src/main/java/woowacourse/chongdaemarket/article/controller/dto/ArticleResponse.java
  src/main/java/woowacourse/chongdaemarket/article/controller/dto/ArticleResponses.java
  src/main/java/woowacourse/chongdaemarket/article/controller/dto/ParticipationCountRequest.java
  src/main/java/woowacourse/chongdaemarket/article/controller/dto/ParticipationCountResponse.java
  src/main/java/woowacourse/chongdaemarket/article/exception/ArticleErrorCode.java
  src/main/java/woowacourse/chongdaemarket/article/repository/Article.java
  src/main/java/woowacourse/chongdaemarket/article/repository/ArticleRepository.java
  src/main/java/woowacourse/chongdaemarket/article/repository/ArticleStatus.java
  src/main/java/woowacourse/chongdaemarket/article/service/ArticleService.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/GroupPurchaseController.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/GroupPurchaseResponse.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/GroupPurchaseResponses.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/ParticipationCountRequest.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/controller/dto/ParticipationCountResponse.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/exception/GroupPurchaseErrorCode.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/repository/GroupPurchaseRepository.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/repository/GroupPurchaseStatus.java
  src/main/java/woowacourse/chongdaemarket/grouppurchase/service/GroupPurchaseService.java
  src/main/resources/data.sql
Labels: refactor

#15 refactor: API 리팩토링
  src/main/java/woowacourse/chongdaemarket/article/controller/dto/ArticleResponse.java
  src/main/java/woowacourse/chongdaemarket/article/controller/dto/ParticipationCountRequest.java
  src/main/java/woowacourse/chongdaemarket/article/exception/ArticleErrorCode.java
  src/main/java/woowacourse/chongdaemarket/article/repository/Article.java
  src/main/java/woowacourse/chongdaemarket/article/service/ArticleService.java
Labels: refactor

#17 refactor: 예외처리 JSON 전달
  src/main/java/woowacourse/chongdaemarket/article/exception/ArticleErrorCode.java
  src/main/java/woowacourse/chongdaemarket/global/exception/ErrorMessage.java
  src/main/java/woowacourse/chongdaemarket/global/exception/ErrorResponse.java
  src/main/java/woowacourse/chongdaemarket/global/exception/GlobalExceptionHandler.java
Labels: refactor

#19 test: test 코드 및 더미데이터 추가
  build.gradle
  src/main/resources/data.sql
  src/test/java/woowacourse/chongdaemarket/ChongdaemarketApplicationTests.java
  src/test/java/woowacourse/chongdaemarket/article/controller/ArticleControllerTest.java
Labels: test

#21 fix: API 명세와 상이한 부분 수정
  http/article.http
  src/main/java/woowacourse/chongdaemarket/article/controller/dto/ArticleResponse.java
  src/main/java/woowacourse/chongdaemarket/article/repository/ArticleStatus.java
Labels: bug/error
